[build]
  base = "public"
  publish = "."
  functions = "validator"

[[redirects]]
  from = "/validator/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/system-assessments.html"
  to = "/pages/system-assessment.html"
  status = 301

[[redirects]]
  from = "/system-assessment.html"
  to = "/pages/system-assessment.html"
  status = 301
